version: '2'
services:
  mysql:
    image: mysql:5.5
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=sanitize
      - MYSQL_USER=sanitize
      - MYSQL_PASSWORD=sanitize
  drupal:
    build: .
    volumes:
      - ./.data/drupal/files:/var/www/html/sites/default/files
      - ./.data/drupal/settings.php:/var/www/html/sites/default/settings.php
      - ./.data/php/php.ini:/usr/local/etc/php/php.ini
      - ./docroot/sites/all/modules/custom:/var/www/html/sites/all/modules/custom
      - ./docroot/sites/all/modules/contrib:/var/www/html/sites/all/modules/contrib
  nginx:
    image: gabesullice/drocker-nginx
    links:
      - drupal:php-fpm
    volumes_from:
      - drupal
    volumes:
      - ./docroot/sites/all/modules/custom:/var/www/html/sites/all/modules/custom
    ports:
      - 80:80
